#!/bin/bash
#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q debug
#SBATCH -J cs5220
#SBATCH -t 00:30:00

#run the application:
# srun -n 1 -c 1 --cpu_bind=cores ./serial -o serial.parts.out -n 1000 -s 150
srun -n 1 -c 1 --cpu_bind=cores ./naive

